# Generated by Django 5.0.3 on 2024-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_post_user_album_photo_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
            ],
        ),
    ]
